### ISSUE TITLE
ts used cdn failure

### ISSUE THREAD

**Issue by LeedaCode** [englercj/playground#7]
Pixijs-ts used by the playground:https://cdn.rawgit.com/pixijs/pixi-typescript/master/pixi.js.d.ts。Become inaccessible

**Comment by englercj** [comment]
Seems to be downloading for me? https://cdn.rawgit.com/pixijs/pixi-typescript/master/pixi.js.d.ts

**Comment by englercj** [comment]
However, now that v5 is released it is using the wrong one so I should fix that.

**Comment by LeedaCode** [comment]
yes.This rawgit service is about to be shut down and has become inaccessible in Asia, so I think a more stable CDN should be replaced.

**Comment by bigtimebuddy** [comment]
@englercj we could start hosting the typings on pixijs.download instead? Would just need a small tweak to the Travis scripts.

**Comment by englercj** [comment]
I think the typings built by pixi should be included (if they aren't yet) in what is stored on S3 (and is therefore exposed on pixijs.download).

But for the older versions I loaded from pixi-typescript may have to do something special there.

**Comment by englercj** [comment]
@bigtimebuddy I just realized that CloudFront doesn't work well in China so using that CDN for the TS may not actually fix this issue.

**Comment by englercj** [comment]
Fixed by 9d73824c38098e45c0a04e2c8489ff17aba2ad8f.

I now host all the old versions of pixi (v4 & v5) myself and distribute them via CloudFlare (which should work in China). For newer versions I'll use pixijs.download as they become available.

**Comment by LeedaCode** [comment]
Thank you very much！
