### ISSUE TITLE
Can you tell me to deploy the playground in liunx?

### ISSUE THREAD

**Issue by LeedaCode** [englercj/playground#8]
Hi! I have an idea,Because http://www.pixiplayground.com. does not allow cross-domain, so many of my projects can not use pictures, this is a very headache. I think I can deploy pixi's playground in my liunx server. I don't know if it is allowed. How should I deploy it? I don't want to use npm run dev,but I want to actually deploy it on the server.

**Comment by englercj** [comment]
The deploy process is not well documented, but is entirely scripted so you can read through the scripts to see how they work.

However, I'd rather just fix whatever issues you are encountering on the live site. What do you mean by it doesn't allow cross-domain? Loading cross domain issues is up to two things being correct: 1) Your server that serves the images must allow cross-domain loading, 2) You must load the image as cross-domain (pixi loader should handle this for you in most cases).

**Comment by LeedaCode** [comment]
http.ts:34 GET https://cdn.rawgit.com/pixijs/pixi-typescript/master/pixi.js.d.ts net::ERR_CONNECTION_TIMED_OUT
sendRequest @ http.ts:34
get @ http.ts:39
getTypings @ index.ts:50
./src/pages/Editor.tsx.Editor.loadTypings @ Editor.tsx:98
./src/pages/Editor.tsx.Editor.onEditorMount @ Editor.tsx:125
./src/components/MonacoEditor.tsx.MonacoEditor.editorDidMount @ MonacoEditor.tsx:76
./src/components/MonacoEditor.tsx.MonacoEditor.initMonaco @ MonacoEditor.tsx:143
(anonymous) @ MonacoEditor.tsx:100
t._invokeFactory @ loader.js:8
t.complete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._resolve @ loader.js:8
s.defineModule @ loader.js:8
o @ loader.js:8
d @ editor.main.js:7
t._invokeFactory @ loader.js:8
t.complete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._onModuleComplete @ loader.js:8
s._resolve @ loader.js:8
s.defineModule @ loader.js:8
o @ loader.js:9
(anonymous) @ editor.main.nls.js:6
Renderer.js:49 Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
    at Function.create (Renderer.js:49)
    at autoDetectRenderer (autoDetectRenderer.js:36)
    at new Application (Application.js:65)
    at demo.js:8
    at updateDemoCode (VM254 results.f93c2e6665930b2ee707.js:18)
    at VM254 results.f93c2e6665930b2ee707.js:13
    at HTMLScriptElement.next (VM254 results.f93c2e6665930b2ee707.js:21)
create @ Renderer.js:49
autoDetectRenderer @ autoDetectRenderer.js:36
Application @ Application.js:65
(anonymous) @ demo.js:8
updateDemoCode @ results.f93c2e6665930b2ee707.js:18
(anonymous) @ results.f93c2e6665930b2ee707.js:13
next @ results.f93c2e6665930b2ee707.js:21
load (async)
loadScript @ results.f93c2e6665930b2ee707.js:19
next @ results.f93c2e6665930b2ee707.js:21
eachSeries @ results.f93c2e6665930b2ee707.js:21
updateScripts @ results.f93c2e6665930b2ee707.js:17
updateDemo @ results.f93c2e6665930b2ee707.js:13
handleMessage @ results.f93c2e6665930b2ee707.js:11
postMessage (async)
./src/pages/Editor.tsx.Editor._onResultIFrameLoaded @ Editor.tsx:209
load (async)
./src/pages/Editor.tsx.Editor.onResultIFrameMount @ Editor.tsx:134
setAccessor @ preact.mjs:134
diffAttributes @ preact.mjs:403
idiff @ preact.mjs:282
innerDiffNode @ preact.mjs:342
idiff @ preact.mjs:279
innerDiffNode @ preact.mjs:342
idiff @ preact.mjs:279
diff @ preact.mjs:205
renderComponent @ preact.mjs:560
renderComponent @ preact.mjs:546
setComponentProps @ preact.mjs:467
buildComponentFromVNode @ preact.mjs:633
idiff @ preact.mjs:244
diff @ preact.mjs:205
render @ preact.mjs:700
./src/index.ts @ index.ts:6
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

**Comment by LeedaCode** [comment]
This is the problem I encountered on my current visit to playground

**Comment by englercj** [comment]
That issue is being tracked by #7
