### ISSUE TITLE
pixijs.download/dev/pixi-legacy.js/types/pixi.js.d.ts:1 Failed to load resource: the server 

### ISSUE THREAD

**Issue by djmisterjon** [englercj/playground#9]
hi i don't know if it related to playground or pixi servor !
was worked 1 or 2 days ago, i change nothing, and today i open and i get this error.
So it maybe a very recent commit somewhere ?

![image](https://user-images.githubusercontent.com/24865815/60468271-1dda1580-9c27-11e9-8b77-dc6f26d8cd54.png)

step to reproduce.
Open a new play ground and add legacy link
`https://pixijs.download/dev/pixi-legacy.js`
![image](https://user-images.githubusercontent.com/24865815/60468361-6265b100-9c27-11e9-96c1-de82afed529f.png)

Also The crash will broke projet thats need load external link.

thanks

**Comment by bigtimebuddy** [comment]
These are the correct link for typings:

https://pixijs.download/dev/types/pixi.js.d.ts
https://pixijs.download/dev/types/pixi.js-legacy.d.ts

**Comment by djmisterjon** [comment]
hum am not sure what i need to do with this information?
you mean i need add this here ?
![image](https://user-images.githubusercontent.com/24865815/60469328-431c5300-9c2a-11e9-8d7c-739cd29e9a63.png)

![image](https://user-images.githubusercontent.com/24865815/60469381-6941f300-9c2a-11e9-9edf-9d9646cef9cd.png)

this is the project i used last day and worked fine.
you should see a bunny , but you can see nothing, and only bug i can see is related to sevor error !
https://www.pixiplayground.com/#/edit/KLahFCph5MmXIFST~LDzt

**Comment by djmisterjon** [comment]
the v4 version work fine ! 
https://www.pixiplayground.com/#/edit/jn0iSg7EGgKroLNTgMtXT

**Comment by englercj** [comment]
@bigtimebuddy Looks like the bug is in playground. He is specifying a custom url and then playground is trying to load typings for it by injecting his custom url into the url for type definitions. `https://pixijs.download/<custom-url>/types/pixi.js.d.ts` -> `https://pixijs.download/https://pixijs.download/dev/types/pixi-legacy.js/types/pixi.js.d.ts`

Could be something wrong with my regex or something, not sure will have to debug.

**Comment by djmisterjon** [comment]
ok this is really weird ! i think it not related to `playground` or `pixijs` !? am very lost.
I think it maybe a break change since 26 june somewhere?
because the last time i open the link it was 26 june and was work fine.
can you confirm you can't see sprites demo ?

**I thought it was bugged because I can't see sprites and console show error for sevor!,** but after studying this, it seems that all works well in pixijs !
I can not see sprites loaded from pixi example!
Am really not understand what happened since the 26 june , but all my private clone do the same behavior, i can't see sprites but they exist?!
![image](https://user-images.githubusercontent.com/24865815/60472092-77494100-9c35-11e9-9d3f-d52638e0882e.png)


I apologize if I express myself badly in english, but I try to understand my side too, normally if you do not touch demo you saved, should no break?

**Comment by djmisterjon** [comment]
Haaaaaaaaaaaaaa.
if we add `forceCanvas:true` it work.
![image](https://user-images.githubusercontent.com/24865815/60474683-78806b00-9c41-11e9-830c-54c1edbc24ac.png)

so now we need understand why.
Is can be related to this ?
https://github.com/pixijs/pixi.js/commit/00fd9d93ad25bd6fa11ceb60654641043d3a3709

**Comment by bigtimebuddy** [comment]
If you can reproduce in jsfiddle or codepen, then it’s probably pixi-related and not playground-related.

**Comment by djmisterjon** [comment]
@bigtimebuddy yes you true, now i can confirm is pixi related.
If you comment `forceCanvas:true`  i can't see sprite rendering in codepen.
https://codepen.io/djmisterjon/pen/GbxGbZ
So it related to a pr from last 6 days, am not able to tell you sorry because i get no error ! . :)

**Comment by bigtimebuddy** [comment]
Could you file another issue on pixi.js about this?

**Comment by englercj** [comment]
OK I guess there are two simultaneous issues:

1. A bug in pixi
2. A bug in the typings loading code in playground

I'll fix the second one :)

**Comment by djmisterjon** [comment]
ya sorry i was think it related to playground, because it showed error, but after study this in deep, it related to a pr in last 6 days :)
if you want you can close this, sorry for this  :)
https://github.com/pixijs/pixi.js/issues/5860

**Comment by englercj** [comment]
Pretty sure I fixed this a bit back, but forgot to update this issue.
